package com.example.pokebattlez.battle.model;

import static com.example.pokebattlez.battle.model.Stat.*;

public enum Nature {
    HARDY(ATTACK, ATTACK), LONELY(ATTACK, DEFENCE), ADAMANT(ATTACK, SPECIAL_ATTACK), NAUGHTY(ATTACK, SPECIAL_DEFENCE), BRAVE(ATTACK, SPEED),
    BOLD(DEFENCE, ATTACK), DOCILE(DEFENCE, DEFENCE), IMPISH(DEFENCE, SPECIAL_ATTACK), LAX(DEFENCE, SPECIAL_DEFENCE), RELAXED(DEFENCE, SPEED),
    MODEST(SPECIAL_ATTACK, ATTACK), MILD(SPECIAL_ATTACK, DEFENCE), BASHFUL(SPECIAL_ATTACK, SPECIAL_ATTACK), RASH(SPECIAL_ATTACK, SPECIAL_DEFENCE), QUIET(SPECIAL_ATTACK, SPEED),
    CALM(SPECIAL_DEFENCE, ATTACK), GENTLE(SPECIAL_DEFENCE, DEFENCE), CAREFUL(SPECIAL_DEFENCE, SPECIAL_ATTACK), QUIRKY(SPECIAL_DEFENCE, SPECIAL_DEFENCE), SASSY(SPECIAL_DEFENCE, SPEED),
    TIMID(SPEED, ATTACK), HASTY(SPEED, DEFENCE), JOLLY(SPEED, SPECIAL_ATTACK), NAIVE(SPEED, SPECIAL_DEFENCE), SERIOUS(SPEED, SPEED);

    private final Stat up;
    private final Stat down;

    Nature(Stat up, Stat down) {
        this.up = up;
        this.down = down;
    }

    public Stat getUp() {
        return up;
    }

    public Stat getDown() {
        return down;
    }
}
